import localFont from "next/font/local";
import "./globals.css";
import { getServerSession } from "next-auth";
import NextAuthProvider from "../component/Session/SessionProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Navbar from "@/component/Navbar/Navbar";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "KimStar5 ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthProvider session={session}>
          <div className="container">
            <header >
              <Navbar />
            </header>
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
